file_format: "1"
id: finger6
name: finger6
type: shield
url: https://github.com/MakotoKurauchi/helix
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - finger6_left
  - finger6_right
